### PR TITLE
Adds support for running in a Docker container

### PR DESCRIPTION
**Pull request by politician**
This PR adds support for running OpenAPI-GUI inside a Docker container, adds a Makefile for getting started quickly, and updates the documentation with the 3 step launch procedure (`clone`, `make`, `make start`).

### Motivation
I prefer to run small tools like this inside Docker containers, so that I can manage them in a single place and be certain they are running under isolation and are using the proper dependencies.  Heroku is fantastic, but I wanted to run this locally without all of the `npm` infrastructure -- it saves in `localStorage` after all!

I hope that you will find this small PR useful, and that it leads to a greater adoption of this neat gem.  Cheers!

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Hi @politician thanks for the PR! As I said to @yogendra in https://github.com/Mermade/openapi-gui/pull/15#issuecomment-335881731 - `npm` is **not** required to run openapi-gui, all you need to do is clone the repository and point a web browser at `index.html` on your local filesystem.

Is the `README.md` not clear enough on this point?

At the moment, I'm thinking of adding Docker support only to the wiki. I really don't like the idea of adding a `Makefile` (and thus another optional dependency on `make`) when it may confuse people into thinking the `Makefile` is required to build or run openapi-gui itself. `make` is not really a common part of the js / `npm` infrastructure and is usually not available on Windows.

Anyway, let me know your thoughts, and I will post my current `Dockerfile` to the wiki for comments.

**Comment by politician** [comment]
> I really don't like the idea of adding a Makefile (and thus another optional dependency on make) when it may confuse people into thinking the Makefile is required to build or run openapi-gui itself. make is not really a common part of the js / npm infrastructure and is usually not available on Windows.

If support for Windows is a goal, then I agree that this is reasonable. 

> I'm thinking of adding Docker support only to the wiki. 

That's fine too, but honestly, I just wanted the simplest possible way to start this tool, and for me, that's Docker.  Perhaps you can make a `docker-openapi-gui` repo that contains the Dockerized app for those of us that prefer that way of launching these projects?

**Comment by MikeRalphson** [comment]
@politician yes, Windows support is a goal - in fact it's my primary development platform!

Rather than maintain a separate repo (which I'd probably forget about), I'd probably take `Dockerfile` and `.dockerignore` into the main repo, but without the `Makefile` (for now).

Have a look at the wiki `Dockerfile`, I've aimed for a nice small container size in case I decide to push it to dockerhub / store. Comments?

**Comment by politician** [comment]
The purpose of the split COPY steps is to reduce restart times by leveraging Docker's layer cache.  The way it's written in the wiki will require all package.json deps to be downloaded every time the container is started.

Otherwise, looks good to me.

**Comment by MikeRalphson** [comment]
Interesting! There's a slight advantage to that, that newer dependencies might be pulled in (according to semver rules), but the time to start the container should probably be the more important consideration. If you fix the wiki I can test locally and then we can look at the PR.

**Comment by politician** [comment]
Cool; wiki's been updated, and tested.  This PR can be closed.

**Comment by MikeRalphson** [comment]
If you're happy to remove the `Makefile` for now, I'm happy to merge...

**Pull request merged**
