### PR TITLE
Make OpenAPI GUI an executable NPM Module

### PR DESCRIPTION
**Pull request by yogendra**
- Updated project name to `openapi-gui`
- Changed main script filename
- Updated all the relevant references (Procfile, package.json, etc)
- Updated main script to be executable
- Published on npm

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Why on earth have you published it to npm yourself? Please get it unpublished ASAP.

**Comment by yogendra** [comment]
Apology for that! I didn't intend to name-squat or anything. I had to test the whole thing. 

Anyway I am unable to unpublish it. so I have deprecated it. 

Alternatively, I can add you as a Collaborator, if you want to maintain this going forward.

**Comment by MikeRalphson** [comment]
Apology accepted. I do believe you can unpublish within the first 24 hours. I'm not sure I'm happy not owning the npm package of my own project.

**Comment by yogendra** [comment]
Whats your npm id? I can add you as a collaborator and you can kick me out. Works?

**Comment by MikeRalphson** [comment]
Npm id is mermade. Thanks.

**Comment by yogendra** [comment]
Done! Added you as the owner/maintainer and kicked myself out. Lesson learned. Thanks for that. :)

**Comment by MikeRalphson** [comment]
Many thanks for the PR. Merged.

**Pull request merged**
